# Generated by Django 5.1.1 on 2024-09-10 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True)),
                ('apellido', models.CharField(max_length=150, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.genero')),
            ],
            options={
                'db_table': 'TBL_PERSONA',
            },
        ),
    ]
