# Generated by Django 5.1.1 on 2024-09-10 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.persona')),
                ('peliculas_actuadas', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'TBL_ACTORES',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.persona')),
                ('peliculas_dirigidas', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'TBL_DIRECTORES',
            },
        ),
        migrations.CreateModel(
            name='GeneroPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'TBL_GENERO_PELICULA',
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('anio_estreno', models.CharField(max_length=4, null=True)),
                ('duracion', models.CharField(max_length=45)),
                ('clasificacion', models.CharField(max_length=45, null=True)),
                ('trama', models.TextField(null=True)),
            ],
            options={
                'db_table': 'TBL_PELICULAS',
            },
        ),
        migrations.AlterModelTable(
            name='persona',
            table='TBL_PERSONAS',
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=75, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField()),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
            ],
            options={
                'db_table': 'TBL_USUARIOS',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(null=True)),
                ('fecha_creado', models.DateField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'TBL_COMENTARIOS',
            },
        ),
        migrations.CreateModel(
            name='DirectorPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.director')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pelicula')),
            ],
            options={
                'db_table': 'TBL_PELICULAS_HAS_DIRECTORES',
                'unique_together': {('pelicula', 'director')},
            },
        ),
        migrations.CreateModel(
            name='ActorPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.actor')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pelicula')),
            ],
            options={
                'db_table': 'TBL_PELICULAS_HAS_ACTORES',
                'unique_together': {('pelicula', 'actor')},
            },
        ),
        migrations.CreateModel(
            name='PeliculaGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.generopelicula')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pelicula')),
            ],
            options={
                'db_table': 'TBL_GENERO_X_PELICULA',
                'unique_together': {('pelicula', 'genero_pelicula')},
            },
        ),
        migrations.CreateModel(
            name='Seguido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidos', to='api.usuario')),
                ('usuario_seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='api.usuario')),
            ],
            options={
                'db_table': 'TBL_SEGUIDO',
                'unique_together': {('usuario_seguidor', 'usuario_seguido')},
            },
        ),
        migrations.CreateModel(
            name='Resenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'TBL_RESENIAS',
                'unique_together': {('pelicula', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'TBL_FAVORITOS',
                'unique_together': {('usuario', 'pelicula')},
            },
        ),
        migrations.CreateModel(
            name='Deseada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'TBL_DESEADAS',
                'unique_together': {('usuario', 'pelicula')},
            },
        ),
        migrations.CreateModel(
            name='Vista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'TBL_VISTAS',
                'unique_together': {('usuario', 'pelicula')},
            },
        ),
    ]
